# Generated by Django 3.0.8 on 2020-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=30, null=True)),
                ('salary', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10)),
                ('image', models.ImageField(default='profile_pic.jpg', upload_to='employee_photos')),
            ],
        ),
    ]
