# Generated by Django 3.0.8 on 2020-07-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='picture',
            new_name='image',
        ),
    ]
