# Generated by Django 3.0.8 on 2020-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200716_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='profile_pic.jpg', upload_to='employee_photos'),
        ),
    ]
